//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.lab {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="akun", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class akun : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeranIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PeranId {
            get {
                return this.PeranIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PeranIdField, value) != true)) {
                    this.PeranIdField = value;
                    this.RaisePropertyChanged("PeranId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jadwalPraktikan", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class jadwalPraktikan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_jadwal_praktikanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.jadwal_umum id_jadwal_umumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nrpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_jadwal_praktikan {
            get {
                return this.id_jadwal_praktikanField;
            }
            set {
                if ((this.id_jadwal_praktikanField.Equals(value) != true)) {
                    this.id_jadwal_praktikanField = value;
                    this.RaisePropertyChanged("id_jadwal_praktikan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.jadwal_umum id_jadwal_umum {
            get {
                return this.id_jadwal_umumField;
            }
            set {
                if ((object.ReferenceEquals(this.id_jadwal_umumField, value) != true)) {
                    this.id_jadwal_umumField = value;
                    this.RaisePropertyChanged("id_jadwal_umum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrp {
            get {
                return this.nrpField;
            }
            set {
                if ((object.ReferenceEquals(this.nrpField, value) != true)) {
                    this.nrpField = value;
                    this.RaisePropertyChanged("nrp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jadwal_umum", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class jadwal_umum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.Shift fk_jadwalUmum_ShiftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.kelas fk_jadwalUmum_kelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.matkul fk_jadwalUmum_matakuliahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.periode fk_jadwalUmum_periodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hariField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_jadwal_umumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_kelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_periodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_shiftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kode_mkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.Shift fk_jadwalUmum_Shift {
            get {
                return this.fk_jadwalUmum_ShiftField;
            }
            set {
                if ((object.ReferenceEquals(this.fk_jadwalUmum_ShiftField, value) != true)) {
                    this.fk_jadwalUmum_ShiftField = value;
                    this.RaisePropertyChanged("fk_jadwalUmum_Shift");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.kelas fk_jadwalUmum_kelas {
            get {
                return this.fk_jadwalUmum_kelasField;
            }
            set {
                if ((object.ReferenceEquals(this.fk_jadwalUmum_kelasField, value) != true)) {
                    this.fk_jadwalUmum_kelasField = value;
                    this.RaisePropertyChanged("fk_jadwalUmum_kelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.matkul fk_jadwalUmum_matakuliah {
            get {
                return this.fk_jadwalUmum_matakuliahField;
            }
            set {
                if ((object.ReferenceEquals(this.fk_jadwalUmum_matakuliahField, value) != true)) {
                    this.fk_jadwalUmum_matakuliahField = value;
                    this.RaisePropertyChanged("fk_jadwalUmum_matakuliah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.periode fk_jadwalUmum_periode {
            get {
                return this.fk_jadwalUmum_periodeField;
            }
            set {
                if ((object.ReferenceEquals(this.fk_jadwalUmum_periodeField, value) != true)) {
                    this.fk_jadwalUmum_periodeField = value;
                    this.RaisePropertyChanged("fk_jadwalUmum_periode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hari {
            get {
                return this.hariField;
            }
            set {
                if ((object.ReferenceEquals(this.hariField, value) != true)) {
                    this.hariField = value;
                    this.RaisePropertyChanged("hari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_jadwal_umum {
            get {
                return this.id_jadwal_umumField;
            }
            set {
                if ((this.id_jadwal_umumField.Equals(value) != true)) {
                    this.id_jadwal_umumField = value;
                    this.RaisePropertyChanged("id_jadwal_umum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_kelas {
            get {
                return this.id_kelasField;
            }
            set {
                if ((this.id_kelasField.Equals(value) != true)) {
                    this.id_kelasField = value;
                    this.RaisePropertyChanged("id_kelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_periode {
            get {
                return this.id_periodeField;
            }
            set {
                if ((this.id_periodeField.Equals(value) != true)) {
                    this.id_periodeField = value;
                    this.RaisePropertyChanged("id_periode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_shift {
            get {
                return this.id_shiftField;
            }
            set {
                if ((object.ReferenceEquals(this.id_shiftField, value) != true)) {
                    this.id_shiftField = value;
                    this.RaisePropertyChanged("id_shift");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kode_mk {
            get {
                return this.kode_mkField;
            }
            set {
                if ((object.ReferenceEquals(this.kode_mkField, value) != true)) {
                    this.kode_mkField = value;
                    this.RaisePropertyChanged("kode_mk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shift", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class Shift : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_shiftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime mulaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime selesaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string waktuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_shift {
            get {
                return this.id_shiftField;
            }
            set {
                if ((object.ReferenceEquals(this.id_shiftField, value) != true)) {
                    this.id_shiftField = value;
                    this.RaisePropertyChanged("id_shift");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime mulai {
            get {
                return this.mulaiField;
            }
            set {
                if ((this.mulaiField.Equals(value) != true)) {
                    this.mulaiField = value;
                    this.RaisePropertyChanged("mulai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime selesai {
            get {
                return this.selesaiField;
            }
            set {
                if ((this.selesaiField.Equals(value) != true)) {
                    this.selesaiField = value;
                    this.RaisePropertyChanged("selesai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string waktu {
            get {
                return this.waktuField;
            }
            set {
                if ((object.ReferenceEquals(this.waktuField, value) != true)) {
                    this.waktuField = value;
                    this.RaisePropertyChanged("waktu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="kelas", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class kelas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_kelasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kelas {
            get {
                return this.KelasField;
            }
            set {
                if ((object.ReferenceEquals(this.KelasField, value) != true)) {
                    this.KelasField = value;
                    this.RaisePropertyChanged("Kelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_kelas {
            get {
                return this.id_kelasField;
            }
            set {
                if ((this.id_kelasField.Equals(value) != true)) {
                    this.id_kelasField = value;
                    this.RaisePropertyChanged("id_kelas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="matkul", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class matkul : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kode_mkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mata_kuliahField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kode_mk {
            get {
                return this.kode_mkField;
            }
            set {
                if ((object.ReferenceEquals(this.kode_mkField, value) != true)) {
                    this.kode_mkField = value;
                    this.RaisePropertyChanged("kode_mk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mata_kuliah {
            get {
                return this.mata_kuliahField;
            }
            set {
                if ((object.ReferenceEquals(this.mata_kuliahField, value) != true)) {
                    this.mata_kuliahField = value;
                    this.RaisePropertyChanged("mata_kuliah");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="periode", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class periode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime akhirSemesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime awalSemesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_periodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string semesterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime akhirSemester {
            get {
                return this.akhirSemesterField;
            }
            set {
                if ((this.akhirSemesterField.Equals(value) != true)) {
                    this.akhirSemesterField = value;
                    this.RaisePropertyChanged("akhirSemester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime awalSemester {
            get {
                return this.awalSemesterField;
            }
            set {
                if ((this.awalSemesterField.Equals(value) != true)) {
                    this.awalSemesterField = value;
                    this.RaisePropertyChanged("awalSemester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_periode {
            get {
                return this.id_periodeField;
            }
            set {
                if ((this.id_periodeField.Equals(value) != true)) {
                    this.id_periodeField = value;
                    this.RaisePropertyChanged("id_periode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string semester {
            get {
                return this.semesterField;
            }
            set {
                if ((object.ReferenceEquals(this.semesterField, value) != true)) {
                    this.semesterField = value;
                    this.RaisePropertyChanged("semester");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="praktikan", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class praktikan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.Users UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.AbsensiPraktikan absenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.angkatan angkatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.jurusan jurusanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRP {
            get {
                return this.NRPField;
            }
            set {
                if ((object.ReferenceEquals(this.NRPField, value) != true)) {
                    this.NRPField = value;
                    this.RaisePropertyChanged("NRP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nama {
            get {
                return this.NamaField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaField, value) != true)) {
                    this.NamaField = value;
                    this.RaisePropertyChanged("Nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.Users Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.AbsensiPraktikan absen {
            get {
                return this.absenField;
            }
            set {
                if ((object.ReferenceEquals(this.absenField, value) != true)) {
                    this.absenField = value;
                    this.RaisePropertyChanged("absen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.angkatan angkatan {
            get {
                return this.angkatanField;
            }
            set {
                if ((object.ReferenceEquals(this.angkatanField, value) != true)) {
                    this.angkatanField = value;
                    this.RaisePropertyChanged("angkatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.jurusan jurusan {
            get {
                return this.jurusanField;
            }
            set {
                if ((object.ReferenceEquals(this.jurusanField, value) != true)) {
                    this.jurusanField = value;
                    this.RaisePropertyChanged("jurusan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbsensiPraktikan", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class AbsensiPraktikan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.jadwalPraktikan JadwalPraktikanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NilaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.pertemuan PertemuanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_absensiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.Staff staffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime waktu_absensiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.jadwalPraktikan JadwalPraktikan {
            get {
                return this.JadwalPraktikanField;
            }
            set {
                if ((object.ReferenceEquals(this.JadwalPraktikanField, value) != true)) {
                    this.JadwalPraktikanField = value;
                    this.RaisePropertyChanged("JadwalPraktikan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nilai {
            get {
                return this.NilaiField;
            }
            set {
                if ((this.NilaiField.Equals(value) != true)) {
                    this.NilaiField = value;
                    this.RaisePropertyChanged("Nilai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.pertemuan Pertemuan {
            get {
                return this.PertemuanField;
            }
            set {
                if ((object.ReferenceEquals(this.PertemuanField, value) != true)) {
                    this.PertemuanField = value;
                    this.RaisePropertyChanged("Pertemuan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_absensi {
            get {
                return this.id_absensiField;
            }
            set {
                if ((this.id_absensiField.Equals(value) != true)) {
                    this.id_absensiField = value;
                    this.RaisePropertyChanged("id_absensi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.Staff staff {
            get {
                return this.staffField;
            }
            set {
                if ((object.ReferenceEquals(this.staffField, value) != true)) {
                    this.staffField = value;
                    this.RaisePropertyChanged("staff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime waktu_absensi {
            get {
                return this.waktu_absensiField;
            }
            set {
                if ((this.waktu_absensiField.Equals(value) != true)) {
                    this.waktu_absensiField = value;
                    this.RaisePropertyChanged("waktu_absensi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="angkatan", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class angkatan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeAngkatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TahunAngkatanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeAngkatan {
            get {
                return this.KodeAngkatanField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeAngkatanField, value) != true)) {
                    this.KodeAngkatanField = value;
                    this.RaisePropertyChanged("KodeAngkatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TahunAngkatan {
            get {
                return this.TahunAngkatanField;
            }
            set {
                if ((object.ReferenceEquals(this.TahunAngkatanField, value) != true)) {
                    this.TahunAngkatanField = value;
                    this.RaisePropertyChanged("TahunAngkatan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jurusan", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class jurusan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeJurusanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaJurusanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeJurusan {
            get {
                return this.KodeJurusanField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeJurusanField, value) != true)) {
                    this.KodeJurusanField = value;
                    this.RaisePropertyChanged("KodeJurusan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaJurusan {
            get {
                return this.NamaJurusanField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaJurusanField, value) != true)) {
                    this.NamaJurusanField = value;
                    this.RaisePropertyChanged("NamaJurusan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pertemuan", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class pertemuan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_jenis_pertemuanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_pertemuanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_jenis_pertemuan {
            get {
                return this.id_jenis_pertemuanField;
            }
            set {
                if ((object.ReferenceEquals(this.id_jenis_pertemuanField, value) != true)) {
                    this.id_jenis_pertemuanField = value;
                    this.RaisePropertyChanged("id_jenis_pertemuan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_pertemuan {
            get {
                return this.id_pertemuanField;
            }
            set {
                if ((this.id_pertemuanField.Equals(value) != true)) {
                    this.id_pertemuanField = value;
                    this.RaisePropertyChanged("id_pertemuan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class Staff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_staffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string no_hpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.Users usersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamat {
            get {
                return this.alamatField;
            }
            set {
                if ((object.ReferenceEquals(this.alamatField, value) != true)) {
                    this.alamatField = value;
                    this.RaisePropertyChanged("alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_staff {
            get {
                return this.id_staffField;
            }
            set {
                if ((object.ReferenceEquals(this.id_staffField, value) != true)) {
                    this.id_staffField = value;
                    this.RaisePropertyChanged("id_staff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string no_hp {
            get {
                return this.no_hpField;
            }
            set {
                if ((object.ReferenceEquals(this.no_hpField, value) != true)) {
                    this.no_hpField = value;
                    this.RaisePropertyChanged("no_hp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.Users users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jadwalStaff", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class jadwalStaff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_jadwal_staffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.jadwal_umum jadwal_umumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.Staff staffField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_jadwal_staff {
            get {
                return this.id_jadwal_staffField;
            }
            set {
                if ((this.id_jadwal_staffField.Equals(value) != true)) {
                    this.id_jadwal_staffField = value;
                    this.RaisePropertyChanged("id_jadwal_staff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.jadwal_umum jadwal_umum {
            get {
                return this.jadwal_umumField;
            }
            set {
                if ((object.ReferenceEquals(this.jadwal_umumField, value) != true)) {
                    this.jadwal_umumField = value;
                    this.RaisePropertyChanged("jadwal_umum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.Staff staff {
            get {
                return this.staffField;
            }
            set {
                if ((object.ReferenceEquals(this.staffField, value) != true)) {
                    this.staffField = value;
                    this.RaisePropertyChanged("staff");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modul", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class modul : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string file_modulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_modulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] lokasi_modulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client.lab.matkul matkulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file_modul {
            get {
                return this.file_modulField;
            }
            set {
                if ((object.ReferenceEquals(this.file_modulField, value) != true)) {
                    this.file_modulField = value;
                    this.RaisePropertyChanged("file_modul");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_modul {
            get {
                return this.id_modulField;
            }
            set {
                if ((this.id_modulField.Equals(value) != true)) {
                    this.id_modulField = value;
                    this.RaisePropertyChanged("id_modul");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] lokasi_modul {
            get {
                return this.lokasi_modulField;
            }
            set {
                if ((object.ReferenceEquals(this.lokasi_modulField, value) != true)) {
                    this.lokasi_modulField = value;
                    this.RaisePropertyChanged("lokasi_modul");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.lab.matkul matkul {
            get {
                return this.matkulField;
            }
            set {
                if ((object.ReferenceEquals(this.matkulField, value) != true)) {
                    this.matkulField = value;
                    this.RaisePropertyChanged("matkul");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="upload_file", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class upload_file : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] data_fileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_absensiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_fileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lokasi_fileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_fileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] data_file {
            get {
                return this.data_fileField;
            }
            set {
                if ((object.ReferenceEquals(this.data_fileField, value) != true)) {
                    this.data_fileField = value;
                    this.RaisePropertyChanged("data_file");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_absensi {
            get {
                return this.id_absensiField;
            }
            set {
                if ((this.id_absensiField.Equals(value) != true)) {
                    this.id_absensiField = value;
                    this.RaisePropertyChanged("id_absensi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_file {
            get {
                return this.id_fileField;
            }
            set {
                if ((this.id_fileField.Equals(value) != true)) {
                    this.id_fileField = value;
                    this.RaisePropertyChanged("id_file");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lokasi_file {
            get {
                return this.lokasi_fileField;
            }
            set {
                if ((object.ReferenceEquals(this.lokasi_fileField, value) != true)) {
                    this.lokasi_fileField = value;
                    this.RaisePropertyChanged("lokasi_file");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_file {
            get {
                return this.nama_fileField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_fileField, value) != true)) {
                    this.nama_fileField = value;
                    this.RaisePropertyChanged("nama_file");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="lab.Iadm")]
    public interface Iadm {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetLogin", ReplyAction="http://tempuri.org/Iadm/GetLoginResponse")]
        string GetLogin(client.lab.akun data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/getTimeLogin", ReplyAction="http://tempuri.org/Iadm/getTimeLoginResponse")]
        client.lab.jadwalPraktikan[] getTimeLogin(client.lab.jadwalPraktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/getPraktikanPraktikum", ReplyAction="http://tempuri.org/Iadm/getPraktikanPraktikumResponse")]
        client.lab.jadwalPraktikan[] getPraktikanPraktikum(string nrp, string shift, int periode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/getProfilePraktikan", ReplyAction="http://tempuri.org/Iadm/getProfilePraktikanResponse")]
        client.lab.praktikan getProfilePraktikan(client.lab.praktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/AddPraktikan", ReplyAction="http://tempuri.org/Iadm/AddPraktikanResponse")]
        int AddPraktikan(client.lab.praktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/EditPraktikan", ReplyAction="http://tempuri.org/Iadm/EditPraktikanResponse")]
        int EditPraktikan(string nrp, client.lab.praktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetJurusan", ReplyAction="http://tempuri.org/Iadm/GetJurusanResponse")]
        client.lab.jurusan[] GetJurusan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetAngkatan", ReplyAction="http://tempuri.org/Iadm/GetAngkatanResponse")]
        client.lab.angkatan[] GetAngkatan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetPraktikan", ReplyAction="http://tempuri.org/Iadm/GetPraktikanResponse")]
        client.lab.praktikan[] GetPraktikan(client.lab.praktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/InsertMultiplePraktikan", ReplyAction="http://tempuri.org/Iadm/InsertMultiplePraktikanResponse")]
        int InsertMultiplePraktikan(client.lab.praktikan[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/ViewJadwalUmum", ReplyAction="http://tempuri.org/Iadm/ViewJadwalUmumResponse")]
        client.lab.jadwal_umum[] ViewJadwalUmum(client.lab.jadwal_umum data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetMatKul", ReplyAction="http://tempuri.org/Iadm/GetMatKulResponse")]
        client.lab.matkul[] GetMatKul();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetKelas", ReplyAction="http://tempuri.org/Iadm/GetKelasResponse")]
        client.lab.kelas[] GetKelas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetShift", ReplyAction="http://tempuri.org/Iadm/GetShiftResponse")]
        client.lab.Shift[] GetShift();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/InsertJadwal", ReplyAction="http://tempuri.org/Iadm/InsertJadwalResponse")]
        int InsertJadwal(client.lab.jadwal_umum[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/DeleteJadwal", ReplyAction="http://tempuri.org/Iadm/DeleteJadwalResponse")]
        int DeleteJadwal(client.lab.jadwal_umum data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/getStaffID", ReplyAction="http://tempuri.org/Iadm/getStaffIDResponse")]
        client.lab.Staff[] getStaffID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/getProfileStaff", ReplyAction="http://tempuri.org/Iadm/getProfileStaffResponse")]
        client.lab.Staff getProfileStaff(client.lab.Staff data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetStaffJadwal", ReplyAction="http://tempuri.org/Iadm/GetStaffJadwalResponse")]
        client.lab.jadwalStaff[] GetStaffJadwal(client.lab.jadwalStaff data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/jadwalUmumStaff", ReplyAction="http://tempuri.org/Iadm/jadwalUmumStaffResponse")]
        client.lab.jadwalStaff[] jadwalUmumStaff(client.lab.periode data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/updateJadwalStaff", ReplyAction="http://tempuri.org/Iadm/updateJadwalStaffResponse")]
        int updateJadwalStaff(string id, client.lab.jadwalStaff data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/addPeriode", ReplyAction="http://tempuri.org/Iadm/addPeriodeResponse")]
        int addPeriode(client.lab.periode data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/viewPeriode", ReplyAction="http://tempuri.org/Iadm/viewPeriodeResponse")]
        client.lab.periode[] viewPeriode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetPertemuan", ReplyAction="http://tempuri.org/Iadm/GetPertemuanResponse")]
        client.lab.pertemuan[] GetPertemuan(client.lab.jadwalPraktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/ListPertemuan", ReplyAction="http://tempuri.org/Iadm/ListPertemuanResponse")]
        client.lab.pertemuan[] ListPertemuan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/PostAbsenPraktikan", ReplyAction="http://tempuri.org/Iadm/PostAbsenPraktikanResponse")]
        int PostAbsenPraktikan(client.lab.AbsensiPraktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetAbsensiPraktikans", ReplyAction="http://tempuri.org/Iadm/GetAbsensiPraktikansResponse")]
        client.lab.praktikan[] GetAbsensiPraktikans(client.lab.AbsensiPraktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/AddStaff", ReplyAction="http://tempuri.org/Iadm/AddStaffResponse")]
        int AddStaff(client.lab.Staff data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/EditStaff", ReplyAction="http://tempuri.org/Iadm/EditStaffResponse")]
        int EditStaff(string id_staff, client.lab.Staff data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/KonfirmasiAbsensi", ReplyAction="http://tempuri.org/Iadm/KonfirmasiAbsensiResponse")]
        int KonfirmasiAbsensi(client.lab.AbsensiPraktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/HapusAbsensi", ReplyAction="http://tempuri.org/Iadm/HapusAbsensiResponse")]
        int HapusAbsensi(client.lab.AbsensiPraktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetJadwalPraktikan", ReplyAction="http://tempuri.org/Iadm/GetJadwalPraktikanResponse")]
        client.lab.jadwalPraktikan[] GetJadwalPraktikan(client.lab.jadwalPraktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/AddJadwalPraktikan", ReplyAction="http://tempuri.org/Iadm/AddJadwalPraktikanResponse")]
        int AddJadwalPraktikan(client.lab.jadwalPraktikan[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/DeleteJadwalPraktikan", ReplyAction="http://tempuri.org/Iadm/DeleteJadwalPraktikanResponse")]
        int DeleteJadwalPraktikan(client.lab.jadwalPraktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/TambahAngaktan", ReplyAction="http://tempuri.org/Iadm/TambahAngaktanResponse")]
        int TambahAngaktan(client.lab.angkatan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetModul", ReplyAction="http://tempuri.org/Iadm/GetModulResponse")]
        client.lab.modul GetModul(client.lab.modul data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetIDAbsensiPraktikan", ReplyAction="http://tempuri.org/Iadm/GetIDAbsensiPraktikanResponse")]
        int GetIDAbsensiPraktikan(client.lab.AbsensiPraktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetUpLoadFile", ReplyAction="http://tempuri.org/Iadm/GetUpLoadFileResponse")]
        int GetUpLoadFile(client.lab.upload_file data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IadmChannel : client.lab.Iadm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IadmClient : System.ServiceModel.ClientBase<client.lab.Iadm>, client.lab.Iadm {
        
        public IadmClient() {
        }
        
        public IadmClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IadmClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IadmClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IadmClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLogin(client.lab.akun data) {
            return base.Channel.GetLogin(data);
        }
        
        public client.lab.jadwalPraktikan[] getTimeLogin(client.lab.jadwalPraktikan data) {
            return base.Channel.getTimeLogin(data);
        }
        
        public client.lab.jadwalPraktikan[] getPraktikanPraktikum(string nrp, string shift, int periode) {
            return base.Channel.getPraktikanPraktikum(nrp, shift, periode);
        }
        
        public client.lab.praktikan getProfilePraktikan(client.lab.praktikan data) {
            return base.Channel.getProfilePraktikan(data);
        }
        
        public int AddPraktikan(client.lab.praktikan data) {
            return base.Channel.AddPraktikan(data);
        }
        
        public int EditPraktikan(string nrp, client.lab.praktikan data) {
            return base.Channel.EditPraktikan(nrp, data);
        }
        
        public client.lab.jurusan[] GetJurusan() {
            return base.Channel.GetJurusan();
        }
        
        public client.lab.angkatan[] GetAngkatan() {
            return base.Channel.GetAngkatan();
        }
        
        public client.lab.praktikan[] GetPraktikan(client.lab.praktikan data) {
            return base.Channel.GetPraktikan(data);
        }
        
        public int InsertMultiplePraktikan(client.lab.praktikan[] data) {
            return base.Channel.InsertMultiplePraktikan(data);
        }
        
        public client.lab.jadwal_umum[] ViewJadwalUmum(client.lab.jadwal_umum data) {
            return base.Channel.ViewJadwalUmum(data);
        }
        
        public client.lab.matkul[] GetMatKul() {
            return base.Channel.GetMatKul();
        }
        
        public client.lab.kelas[] GetKelas() {
            return base.Channel.GetKelas();
        }
        
        public client.lab.Shift[] GetShift() {
            return base.Channel.GetShift();
        }
        
        public int InsertJadwal(client.lab.jadwal_umum[] data) {
            return base.Channel.InsertJadwal(data);
        }
        
        public int DeleteJadwal(client.lab.jadwal_umum data) {
            return base.Channel.DeleteJadwal(data);
        }
        
        public client.lab.Staff[] getStaffID() {
            return base.Channel.getStaffID();
        }
        
        public client.lab.Staff getProfileStaff(client.lab.Staff data) {
            return base.Channel.getProfileStaff(data);
        }
        
        public client.lab.jadwalStaff[] GetStaffJadwal(client.lab.jadwalStaff data) {
            return base.Channel.GetStaffJadwal(data);
        }
        
        public client.lab.jadwalStaff[] jadwalUmumStaff(client.lab.periode data) {
            return base.Channel.jadwalUmumStaff(data);
        }
        
        public int updateJadwalStaff(string id, client.lab.jadwalStaff data) {
            return base.Channel.updateJadwalStaff(id, data);
        }
        
        public int addPeriode(client.lab.periode data) {
            return base.Channel.addPeriode(data);
        }
        
        public client.lab.periode[] viewPeriode() {
            return base.Channel.viewPeriode();
        }
        
        public client.lab.pertemuan[] GetPertemuan(client.lab.jadwalPraktikan data) {
            return base.Channel.GetPertemuan(data);
        }
        
        public client.lab.pertemuan[] ListPertemuan() {
            return base.Channel.ListPertemuan();
        }
        
        public int PostAbsenPraktikan(client.lab.AbsensiPraktikan data) {
            return base.Channel.PostAbsenPraktikan(data);
        }
        
        public client.lab.praktikan[] GetAbsensiPraktikans(client.lab.AbsensiPraktikan data) {
            return base.Channel.GetAbsensiPraktikans(data);
        }
        
        public int AddStaff(client.lab.Staff data) {
            return base.Channel.AddStaff(data);
        }
        
        public int EditStaff(string id_staff, client.lab.Staff data) {
            return base.Channel.EditStaff(id_staff, data);
        }
        
        public int KonfirmasiAbsensi(client.lab.AbsensiPraktikan data) {
            return base.Channel.KonfirmasiAbsensi(data);
        }
        
        public int HapusAbsensi(client.lab.AbsensiPraktikan data) {
            return base.Channel.HapusAbsensi(data);
        }
        
        public client.lab.jadwalPraktikan[] GetJadwalPraktikan(client.lab.jadwalPraktikan data) {
            return base.Channel.GetJadwalPraktikan(data);
        }
        
        public int AddJadwalPraktikan(client.lab.jadwalPraktikan[] data) {
            return base.Channel.AddJadwalPraktikan(data);
        }
        
        public int DeleteJadwalPraktikan(client.lab.jadwalPraktikan data) {
            return base.Channel.DeleteJadwalPraktikan(data);
        }
        
        public int TambahAngaktan(client.lab.angkatan data) {
            return base.Channel.TambahAngaktan(data);
        }
        
        public client.lab.modul GetModul(client.lab.modul data) {
            return base.Channel.GetModul(data);
        }
        
        public int GetIDAbsensiPraktikan(client.lab.AbsensiPraktikan data) {
            return base.Channel.GetIDAbsensiPraktikan(data);
        }
        
        public int GetUpLoadFile(client.lab.upload_file data) {
            return base.Channel.GetUpLoadFile(data);
        }
    }
}
