//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.lab {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="akun", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class akun : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeranIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PeranId {
            get {
                return this.PeranIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PeranIdField, value) != true)) {
                    this.PeranIdField = value;
                    this.RaisePropertyChanged("PeranId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jurusan", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class jurusan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeJurusanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaJurusanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeJurusan {
            get {
                return this.KodeJurusanField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeJurusanField, value) != true)) {
                    this.KodeJurusanField = value;
                    this.RaisePropertyChanged("KodeJurusan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaJurusan {
            get {
                return this.NamaJurusanField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaJurusanField, value) != true)) {
                    this.NamaJurusanField = value;
                    this.RaisePropertyChanged("NamaJurusan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="angkatan", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class angkatan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeAngkatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TahunAngkatanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeAngkatan {
            get {
                return this.KodeAngkatanField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeAngkatanField, value) != true)) {
                    this.KodeAngkatanField = value;
                    this.RaisePropertyChanged("KodeAngkatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TahunAngkatan {
            get {
                return this.TahunAngkatanField;
            }
            set {
                if ((object.ReferenceEquals(this.TahunAngkatanField, value) != true)) {
                    this.TahunAngkatanField = value;
                    this.RaisePropertyChanged("TahunAngkatan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="praktikan", Namespace="http://schemas.datacontract.org/2004/07/SvApp")]
    [System.SerializableAttribute()]
    public partial class praktikan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeAngkatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeJurusanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeAngkatan {
            get {
                return this.KodeAngkatanField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeAngkatanField, value) != true)) {
                    this.KodeAngkatanField = value;
                    this.RaisePropertyChanged("KodeAngkatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeJurusan {
            get {
                return this.KodeJurusanField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeJurusanField, value) != true)) {
                    this.KodeJurusanField = value;
                    this.RaisePropertyChanged("KodeJurusan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRP {
            get {
                return this.NRPField;
            }
            set {
                if ((object.ReferenceEquals(this.NRPField, value) != true)) {
                    this.NRPField = value;
                    this.RaisePropertyChanged("NRP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nama {
            get {
                return this.NamaField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaField, value) != true)) {
                    this.NamaField = value;
                    this.RaisePropertyChanged("Nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="lab.Iadm")]
    public interface Iadm {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetLogin", ReplyAction="http://tempuri.org/Iadm/GetLoginResponse")]
        string GetLogin(client.lab.akun data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetJurusan", ReplyAction="http://tempuri.org/Iadm/GetJurusanResponse")]
        client.lab.jurusan[] GetJurusan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetAngkatan", ReplyAction="http://tempuri.org/Iadm/GetAngkatanResponse")]
        client.lab.angkatan[] GetAngkatan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/GetPraktikan", ReplyAction="http://tempuri.org/Iadm/GetPraktikanResponse")]
        client.lab.praktikan[] GetPraktikan(client.lab.praktikan data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadm/InsertMultiplePraktikan", ReplyAction="http://tempuri.org/Iadm/InsertMultiplePraktikanResponse")]
        int InsertMultiplePraktikan(client.lab.praktikan[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IadmChannel : client.lab.Iadm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IadmClient : System.ServiceModel.ClientBase<client.lab.Iadm>, client.lab.Iadm {
        
        public IadmClient() {
        }
        
        public IadmClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IadmClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IadmClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IadmClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLogin(client.lab.akun data) {
            return base.Channel.GetLogin(data);
        }
        
        public client.lab.jurusan[] GetJurusan() {
            return base.Channel.GetJurusan();
        }
        
        public client.lab.angkatan[] GetAngkatan() {
            return base.Channel.GetAngkatan();
        }
        
        public client.lab.praktikan[] GetPraktikan(client.lab.praktikan data) {
            return base.Channel.GetPraktikan(data);
        }
        
        public int InsertMultiplePraktikan(client.lab.praktikan[] data) {
            return base.Channel.InsertMultiplePraktikan(data);
        }
    }
}
